name: super_editor
description: Configurable, composable, extensible text editor and document renderer for Flutter.
version: 0.2.0
homepage: https://github.com/superlistapp/super_editor

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  attributed_text: ^0.1.3
  characters: ^1.2.0
  collection: ^1.15.0
  http: ^0.13.1
  linkify: ^4.0.0
  logging: ^1.0.1
  flutter_test:
    sdk: flutter
  super_text_layout: ^0.1.0
  uuid: ^3.0.3

dependency_overrides:
  # Override to local mono-repo path so devs can test this repo
  # against changes that they're making to other mono-repo packages
  attributed_text:
    path: ../attributed_text
  super_text_layout:
    path: ../super_text_layout

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test_robots: ^0.0.15
  golden_toolkit: ^0.11.0
  mockito: ^5.0.4
  super_editor_markdown:
    path: ../super_editor_markdown
  text_table: ^4.0.1

flutter:
  # no Flutter configuration
